# Generated by Django 6.0 on 2025-12-10 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('architecture', 'Architecture Project'), ('design', 'Design Consultation'), ('game', 'Game Systems Development'), ('research', 'Research Collaboration'), ('exhibition', 'Exhibition/Art Project'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('contacted', 'Contacted'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Atelier Spaces Nate', max_length=200)),
                ('tagline', models.CharField(default='Research-led design studio', max_length=300)),
                ('founder_quote', models.TextField(default='', help_text='Inspirational quote for homepage')),
                ('contact_email', models.EmailField(default='contact@atelierspacesnate.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short preview text', max_length=300)),
                ('content', models.TextField(help_text='Full article content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short project summary')),
                ('full_content', models.TextField(help_text='Detailed project description/process')),
                ('project_type', models.CharField(choices=[('architecture', 'Architecture'), ('design', 'Design'), ('game', 'Game Systems'), ('art', 'Art'), ('speculative', 'Speculative')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/featured/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
