# Generated by Django 6.0 on 2025-12-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('content', models.TextField(help_text='About us content (supports markdown)')),
                ('team_image', models.ImageField(blank=True, help_text='Group photo of the team', null=True, upload_to='about/')),
                ('team_caption', models.TextField(blank=True, help_text='Caption for team image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero image (recommended: 1920x1080)', upload_to='hero/')),
                ('caption', models.CharField(help_text='Short description/caption', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SloganSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='…imagine the kind that has no limits, from which invisible ideas are turned into things people can touch, see, hear and feel…')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slogan Section',
                'verbose_name_plural': 'Slogan Section',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='Position/role in the team', max_length=100)),
                ('bio', models.TextField(help_text='Member biography')),
                ('image', models.ImageField(help_text='Member photo', upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('omweso', 'Omweso'), ('kinsman', 'The Kinsman Challenge'), ('design', 'Design'), ('architecture', 'Architecture'), ('royal_toast', 'The Royal Toast Games'), ('art_projects', 'Nate Art Projects')], max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the category', max_length=100)),
                ('image', models.ImageField(help_text='Category featured image', upload_to='categories/')),
                ('description', models.TextField(help_text='Brief description of this category')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Category',
                'verbose_name_plural': 'Work Categories',
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('featured_image', models.ImageField(help_text='Main work image', upload_to='works/')),
                ('description', models.TextField(help_text='Description of the work')),
                ('full_content', models.TextField(blank=True, help_text='Detailed content (optional)')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='works/gallery/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='works/gallery/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='works/gallery/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='works/gallery/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in Featured Works section')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.workcategory')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
